### ISSUE TITLE
memcached version used in Netflix

### ISSUE THREAD

**Issue by mckelvin** [Netflix/rend#19]
I'm curious about the project. In README, it says:

> In order to use the proxy, it is required to have a memcached running on the local machine. THe recommended version is the latest version, currently 1.4.25. This version has the full set of features used by the proxy as well as a bunch of performance and stability improvements. **It is the same one we use at Netflix for production use cases.**

Does the highlighted sentence means all memcached instances running in Netflix are of version 1.4.25? Or, just part of them(instances for rend) are of this version. Looking forward to your reply since updating a software from an old version is not easy.

BTW: `THe` (in README) should be a typo.

**Comment by ScottMansfield** [comment]
I will remove that line in bold. It's incorrect and therefore misleading. 

As for the specific versions we use internally, I can't answer that. I can tell you that 1.4.25 is much better than the older versions of memcached. You can look at the release notes to see what has changed and judge for yourself if it is worth upgrading.

Thank you as well for pointing out the typo. We had a pull request already to fix that which has been merged.

I'm closing this as I believe I've answered the best I can.
