### ISSUE TITLE
Clients unable to connect

### ISSUE THREAD

**Issue by senugula** [Netflix/rend#41]
Here is the error
Recovered from runtime panic: interface conversion: interface is nil, not common.GetRequest
Panic location:  Panic occured at: /mnt/builds/slave/workspace/rend/gopkg/src/github.com/netflix/rend/memproxy.go:main.handleConnection (line 366)

This line suggests like a metrics increment.

**Comment by ScottMansfield** [comment]
The binary protocol does not respond properly when it encounters an unknown opcode. It replies with a nil struct, common.RequestGet, and a nil error causing this error when the main program loop tries to decode the parsed request. The nil error meant the error checking code couldn't do its job and casting the nil to common.GetRequest failed.

The solution is pretty simple: Respond with the proper error when the command is unrecognized.

**Comment by ScottMansfield** [comment]
this was fixed in 89ef7b51646e6054cfc7e10718d924a152dcbbbb
