### ISSUE TITLE
Use bucket histograms as well for collecting latency metrics

### ISSUE THREAD

**Issue by ScottMansfield** [Netflix/rend#55]
These aren't as accurate in terms of percentiles but aggregate much better across fleets. The Atlas metrics system inside Netflix also has support for bucketized metrics aggregation that we currently can't take advantage of because the data is not placed into fixed buckets. 

This would help us get fleet-wide percentiles that are still approximations, but at least have some basis in sound math and statistics instead of our current average-of-95th method.

**Comment by dgryski** [comment]
Fast binary linear-log bucketing: https://github.com/dgryski/go-linlog

**Comment by ScottMansfield** [comment]
I'm considering using a count of leading zeros to get the bucket number to use, which will increase the buckets by power of two and be fast, as long as the count of leading zeros is fast. It's likely I'll be using this assembly implementation to do so:

https://github.com/dgryski/go-bits/blob/master/clz_amd64.s

**Comment by ScottMansfield** [comment]
Actually LZCNT (https://en.wikipedia.org/wiki/SSE4#POPCNT_and_LZCNT) might be simpler, since it does exactly what I need. It's a simpler implementation since it only uses a single instruction (though with the overhead of a function call still) and is supported by the hardware that we run on.

**Comment by ScottMansfield** [comment]
Turns out the processors we run on have POPCNT but not LZCNT (we apparently aren't on Haswell yet, boo) to BSRQ it is.
